# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestZxc():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_zxc(self):
    self.driver.get("https://eios.sibsutis.ru/login/index.php")
    self.driver.set_window_size(1581, 911)
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(3)").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("dima.tryshkanov89@mail.ru")
    self.driver.find_element(By.CSS_SELECTOR, ".col-md-5:nth-child(2)").click()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Ogubot22.")
    self.driver.find_element(By.ID, "loginbtn").click()
    self.driver.find_element(By.CSS_SELECTOR, "#quiznavbutton49 > .thispageholder").click()
    self.driver.find_element(By.ID, "q311652:49_answer1").click()
    self.driver.find_element(By.CSS_SELECTOR, "#q311652\\3A 49_answer0_label .img-responsive").click()
    self.driver.find_element(By.ID, "mod_quiz-next-nav").click()
  
