# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDrag():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_drag(self):
    self.driver.get("https://eios.sibsutis.ru/mod/quiz/attempt.php?attempt=273360&cmid=79484&page=1")
    self.driver.set_window_size(1581, 911)
    self.vars["qwe"] = self.driver.find_element(By.XPATH, "//div[2]/div/div/div/p").text
    self.driver.find_element(By.ID, "mod_quiz-next-nav").click()
  
